### ISSUE TITLE
Data Directory 

### ISSUE THREAD

**Issue by wanglikun1973** [palexandremello/goes-py#2]
This is a very nice package. For the future version, would you like to make the directory (that is used to save downloaded data) as input parameter also? Right now, I see this is set as home directory. Thanks, 

Likun Wang

**Comment by spestana** [comment]
Hi @wanglikun1973 , this is something I added in [my fork](https://github.com/spestana/goes-py) so that the first argument in ABI_Downloader is the "home" directory I'd like to download the ABI products to.

`ABI_Downloader(directory, bucket, year, month, day, hour, product, channel)`

I've submitted a pull request to add this feature here too. I hope this helps!

**Comment by palexandremello** [comment]
Thanks so much @spestana to add that feature.

**Comment by wanglikun1973** [comment]
Thank you for your new features. I just find there is Himawari-8 AHI data on AWS, see link here  
https://aws.amazon.com/blogs/publicsector/himawari-8-enabling-access-key-weather-data/

Would you like to add a feature to download AHI data also? Thanks,

**Comment by spestana** [comment]
That's great, thanks for the suggestion @wanglikun1973 ! I've opened [a separate issue ](https://github.com/palexandremello/goes-py/issues/4)for adding an AHI downloader.

We should be able to close this issue now since it was fixed with this [PR](https://github.com/palexandremello/goes-py/pull/3)?

**Comment by wanglikun1973** [comment]
yes, Thank you for your quick response.
